sudo: required

language: ruby

services:
  - docker

install:
  - docker build -t johntfoster/tadiga .

script:
  - docker run johntfoster/tadiga /bin/sh -c "cd /tadiga/build; make test"

after_success:
  - docker run johntfoster/tadiga /bin/sh -c "rm -rf /tadiga"
  - docker commit (docker ps -a | awk '/tadiga/{print $1}') johntfoster/tadiga
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push johntfoster/tadiga;
    fi


