sudo: required

language: ruby

services:
  - docker

install:
  - docker build -t johntfoster/trilinos:tadiga .

script:
  - docker run -d -t johntfoster/trilinos:tadiga
  - docker ps

after_success:
  - if [ "$TRAVIS_BRANCH" == "trilinos" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push johntfoster/trilinos:tadiga;
    fi


